cuda_visible_devices: 3

log_mlflow: False
mlflow_experiment: sae_recsys_gpt
run_name: ml-20m
save_model: True

data_path: /home/jovyan/mlruns/311478491323376785/7c9094befe4a444399dcb1ec705b23b7/artifacts/

dataset_params:
  max_length: 64
  time_col: timestamp

dataloader:
  batch_size: 128
  test_batch_size: 256
  num_workers: 8
  validation_size: 10000

gpt_config:
  vocab_size: 2
  n_positions: ${dataset_params.max_length}
  n_embd: 64
  n_layer: 2
  n_head: 2

seqrec_module:
  lr: 0.001
  predict_top_k: 10
  filter_seen: True

trainer_params:
  max_epochs: 100
patience: 10